# Generated by Django 2.2.12 on 2020-06-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=200, verbose_name='schema name')),
                ('schema_description', models.CharField(blank=True, max_length=200, verbose_name='schema_description')),
                ('string1', models.CharField(max_length=200, verbose_name='string1')),
                ('string2', models.CharField(blank=True, max_length=200, verbose_name='string2')),
                ('string3', models.CharField(blank=True, max_length=200, verbose_name='string3')),
                ('string4', models.CharField(blank=True, max_length=200, verbose_name='string4')),
                ('string5', models.CharField(blank=True, max_length=200, verbose_name='string5')),
                ('string6', models.CharField(blank=True, max_length=200, verbose_name='string6')),
                ('string7', models.CharField(blank=True, max_length=200, verbose_name='string7')),
                ('string8', models.CharField(blank=True, max_length=200, verbose_name='string8')),
                ('string9', models.CharField(blank=True, max_length=200, verbose_name='string9')),
                ('string10', models.CharField(blank=True, max_length=200, verbose_name='string10')),
                ('date1', models.CharField(blank=True, max_length=200, verbose_name='date1')),
                ('date2', models.CharField(blank=True, max_length=200, verbose_name='date2')),
                ('date3', models.CharField(blank=True, max_length=200, verbose_name='date3')),
                ('date4', models.CharField(blank=True, max_length=200, verbose_name='date4')),
                ('date5', models.CharField(blank=True, max_length=200, verbose_name='date5')),
                ('float1', models.CharField(blank=True, max_length=200, verbose_name='float1')),
                ('float2', models.CharField(blank=True, max_length=200, verbose_name='float2')),
                ('float3', models.CharField(blank=True, max_length=200, verbose_name='float3')),
                ('float4', models.CharField(blank=True, max_length=200, verbose_name='float4')),
                ('float5', models.CharField(blank=True, max_length=200, verbose_name='float5')),
                ('int1', models.CharField(blank=True, max_length=200, verbose_name='int1')),
                ('int2', models.CharField(blank=True, max_length=200, verbose_name='int2')),
                ('int3', models.CharField(blank=True, max_length=200, verbose_name='int3')),
                ('int4', models.CharField(blank=True, max_length=200, verbose_name='int4')),
                ('int5', models.CharField(blank=True, max_length=200, verbose_name='int5')),
                ('status', models.CharField(blank=True, max_length=200, verbose_name='status')),
                ('photo', models.ImageField(default='/media/placeholder.jpeg', upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Schemas',
            },
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string1', models.CharField(max_length=200, verbose_name='string1')),
                ('string2', models.CharField(blank=True, max_length=200, verbose_name='string2')),
                ('string3', models.CharField(blank=True, max_length=200, verbose_name='string3')),
                ('string4', models.CharField(blank=True, max_length=200, verbose_name='string4')),
                ('string5', models.CharField(blank=True, max_length=200, verbose_name='string5')),
                ('string6', models.CharField(blank=True, max_length=200, verbose_name='string6')),
                ('string7', models.CharField(blank=True, max_length=200, verbose_name='string7')),
                ('string8', models.CharField(blank=True, max_length=200, verbose_name='string8')),
                ('string9', models.CharField(blank=True, max_length=200, verbose_name='string9')),
                ('string10', models.CharField(blank=True, max_length=200, verbose_name='string10')),
                ('date1', models.DateField(blank=True, default=None, null=True, verbose_name='date1')),
                ('date2', models.DateField(blank=True, default=None, null=True, verbose_name='date2')),
                ('date3', models.DateField(blank=True, default=None, null=True, verbose_name='date3')),
                ('date4', models.DateField(blank=True, default=None, null=True, verbose_name='date4')),
                ('date5', models.DateField(blank=True, default=None, null=True, verbose_name='date5')),
                ('float1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float1')),
                ('float2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float2')),
                ('float3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float3')),
                ('float4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float4')),
                ('float5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float5')),
                ('int1', models.IntegerField(blank=True, null=True, verbose_name='int1')),
                ('int2', models.IntegerField(blank=True, null=True, verbose_name='int2')),
                ('int3', models.IntegerField(blank=True, null=True, verbose_name='int3')),
                ('int4', models.IntegerField(blank=True, null=True, verbose_name='int4')),
                ('int5', models.IntegerField(blank=True, null=True, verbose_name='int5')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DEFERRED', 'Deferred'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('schema_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Schema', verbose_name='schema name')),
            ],
            options={
                'verbose_name_plural': 'Generic Datasets',
            },
        ),
    ]
