# Generated by Django 2.2.12 on 2020-05-19 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200519_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 14, 11, 27, 621853), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
