# Generated by Django 2.2.12 on 2020-05-19 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200519_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 14, 35, 4, 137194), verbose_name='Date of Birth'),
        ),
    ]
