# Generated by Django 2.2.12 on 2020-05-19 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200519_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 19, 11, 6, 234139), verbose_name='Date of Birth'),
        ),
    ]
