# Generated by Django 2.2.12 on 2020-05-21 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200521_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
    ]
