# Generated by Django 2.2.12 on 2020-05-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200521_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ContactType', verbose_name='Contact Type'),
        ),
    ]
