# Generated by Django 2.2.12 on 2020-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200522_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mktg_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
