# Generated by Django 2.2.12 on 2020-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact_mktg_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mktg_opt_in',
            field=models.BooleanField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='TRUE', max_length=1),
        ),
    ]
