# Generated by Django 2.2.12 on 2020-05-22 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_generic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=200, verbose_name='string1')),
                ('string1', models.CharField(max_length=200, verbose_name='string1')),
                ('string2', models.CharField(max_length=200, verbose_name='string2')),
                ('string3', models.CharField(max_length=200, verbose_name='string3')),
                ('string4', models.CharField(max_length=200, verbose_name='string4')),
                ('string5', models.CharField(max_length=200, verbose_name='string5')),
                ('date1', models.DateField(default=django.utils.timezone.now, verbose_name='date1')),
                ('date2', models.DateField(default=django.utils.timezone.now, verbose_name='date2')),
                ('date3', models.DateField(default=django.utils.timezone.now, verbose_name='date3')),
            ],
            options={
                'verbose_name_plural': 'Schemas',
            },
        ),
        migrations.RemoveField(
            model_name='generic',
            name='data_type',
        ),
        migrations.AddField(
            model_name='generic',
            name='schema_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Schema', verbose_name='schema name'),
        ),
    ]
