# Generated by Django 2.2.12 on 2020-05-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200522_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='schema_name',
            field=models.CharField(max_length=200, verbose_name='schema name'),
        ),
    ]
