# Generated by Django 2.2.12 on 2020-05-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200522_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='date1',
            field=models.CharField(max_length=200, verbose_name='date1'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='date2',
            field=models.CharField(max_length=200, verbose_name='date2'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='date3',
            field=models.CharField(max_length=200, verbose_name='date3'),
        ),
    ]
