# Generated by Django 2.2.12 on 2020-05-22 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200522_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic',
            name='date1',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='date1'),
        ),
        migrations.AlterField(
            model_name='generic',
            name='date2',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='date2'),
        ),
        migrations.AlterField(
            model_name='generic',
            name='date3',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='date3'),
        ),
        migrations.AlterField(
            model_name='generic',
            name='string2',
            field=models.CharField(blank=True, max_length=200, verbose_name='string2'),
        ),
        migrations.AlterField(
            model_name='generic',
            name='string3',
            field=models.CharField(blank=True, max_length=200, verbose_name='string3'),
        ),
        migrations.AlterField(
            model_name='generic',
            name='string4',
            field=models.CharField(blank=True, max_length=200, verbose_name='string4'),
        ),
        migrations.AlterField(
            model_name='generic',
            name='string5',
            field=models.CharField(blank=True, max_length=200, verbose_name='string5'),
        ),
    ]
