# Generated by Django 2.2.12 on 2020-05-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200522_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='amount1',
            field=models.CharField(blank=True, max_length=200, verbose_name='amount1'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='amount2',
            field=models.CharField(blank=True, max_length=200, verbose_name='amount2'),
        ),
    ]
