# Generated by Django 2.2.12 on 2020-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200522_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='status',
            field=models.CharField(blank=True, max_length=200, verbose_name='status'),
        ),
    ]
