# Generated by Django 2.2.12 on 2020-05-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_schema_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='photo',
            field=models.ImageField(default='/media/placeholder.jpeg', upload_to='media'),
        ),
    ]
