# Generated by Django 2.2.12 on 2020-05-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200525_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic',
            name='amount1',
        ),
        migrations.RemoveField(
            model_name='generic',
            name='amount2',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='amount1',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='amount2',
        ),
        migrations.AddField(
            model_name='generic',
            name='date4',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date4'),
        ),
        migrations.AddField(
            model_name='generic',
            name='date5',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date5'),
        ),
        migrations.AddField(
            model_name='generic',
            name='float1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float1'),
        ),
        migrations.AddField(
            model_name='generic',
            name='float2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float2'),
        ),
        migrations.AddField(
            model_name='generic',
            name='float3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float3'),
        ),
        migrations.AddField(
            model_name='generic',
            name='float4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float4'),
        ),
        migrations.AddField(
            model_name='generic',
            name='float5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='float5'),
        ),
        migrations.AddField(
            model_name='generic',
            name='int1',
            field=models.IntegerField(blank=True, null=True, verbose_name='int1'),
        ),
        migrations.AddField(
            model_name='generic',
            name='int2',
            field=models.IntegerField(blank=True, null=True, verbose_name='int2'),
        ),
        migrations.AddField(
            model_name='generic',
            name='int3',
            field=models.IntegerField(blank=True, null=True, verbose_name='int3'),
        ),
        migrations.AddField(
            model_name='generic',
            name='int4',
            field=models.IntegerField(blank=True, null=True, verbose_name='int4'),
        ),
        migrations.AddField(
            model_name='generic',
            name='int5',
            field=models.IntegerField(blank=True, null=True, verbose_name='int5'),
        ),
        migrations.AddField(
            model_name='generic',
            name='string10',
            field=models.CharField(blank=True, max_length=200, verbose_name='string10'),
        ),
        migrations.AddField(
            model_name='generic',
            name='string6',
            field=models.CharField(blank=True, max_length=200, verbose_name='string6'),
        ),
        migrations.AddField(
            model_name='generic',
            name='string7',
            field=models.CharField(blank=True, max_length=200, verbose_name='string7'),
        ),
        migrations.AddField(
            model_name='generic',
            name='string8',
            field=models.CharField(blank=True, max_length=200, verbose_name='string8'),
        ),
        migrations.AddField(
            model_name='generic',
            name='string9',
            field=models.CharField(blank=True, max_length=200, verbose_name='string9'),
        ),
        migrations.AddField(
            model_name='schema',
            name='date4',
            field=models.CharField(blank=True, max_length=200, verbose_name='date4'),
        ),
        migrations.AddField(
            model_name='schema',
            name='date5',
            field=models.CharField(blank=True, max_length=200, verbose_name='date5'),
        ),
        migrations.AddField(
            model_name='schema',
            name='float1',
            field=models.CharField(blank=True, max_length=200, verbose_name='float1'),
        ),
        migrations.AddField(
            model_name='schema',
            name='float2',
            field=models.CharField(blank=True, max_length=200, verbose_name='float2'),
        ),
        migrations.AddField(
            model_name='schema',
            name='float3',
            field=models.CharField(blank=True, max_length=200, verbose_name='float3'),
        ),
        migrations.AddField(
            model_name='schema',
            name='float4',
            field=models.CharField(blank=True, max_length=200, verbose_name='float4'),
        ),
        migrations.AddField(
            model_name='schema',
            name='float5',
            field=models.CharField(blank=True, max_length=200, verbose_name='float5'),
        ),
        migrations.AddField(
            model_name='schema',
            name='int1',
            field=models.CharField(blank=True, max_length=200, verbose_name='int1'),
        ),
        migrations.AddField(
            model_name='schema',
            name='int2',
            field=models.CharField(blank=True, max_length=200, verbose_name='int2'),
        ),
        migrations.AddField(
            model_name='schema',
            name='int3',
            field=models.CharField(blank=True, max_length=200, verbose_name='int3'),
        ),
        migrations.AddField(
            model_name='schema',
            name='int4',
            field=models.CharField(blank=True, max_length=200, verbose_name='int4'),
        ),
        migrations.AddField(
            model_name='schema',
            name='int5',
            field=models.CharField(blank=True, max_length=200, verbose_name='int5'),
        ),
        migrations.AddField(
            model_name='schema',
            name='string10',
            field=models.CharField(blank=True, max_length=200, verbose_name='string10'),
        ),
        migrations.AddField(
            model_name='schema',
            name='string6',
            field=models.CharField(blank=True, max_length=200, verbose_name='string6'),
        ),
        migrations.AddField(
            model_name='schema',
            name='string7',
            field=models.CharField(blank=True, max_length=200, verbose_name='string7'),
        ),
        migrations.AddField(
            model_name='schema',
            name='string8',
            field=models.CharField(blank=True, max_length=200, verbose_name='string8'),
        ),
        migrations.AddField(
            model_name='schema',
            name='string9',
            field=models.CharField(blank=True, max_length=200, verbose_name='string9'),
        ),
    ]
