# Generated by Django 2.2.12 on 2020-05-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200525_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='schema_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='schema_description'),
        ),
    ]
