# Generated by Django 2.2.12 on 2020-06-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_schema_schema_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='string1')),
                ('description', models.CharField(max_length=200, verbose_name='string1')),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
